"""Task definitions for the research agent pipeline."""

from crewai import Task


def make_tasks(topic: str, researcher, analyst, writer):
    """Create the three sequential tasks for the research pipeline.

    Args:
        topic: The research topic.
        researcher: The Senior Research Analyst agent.
        analyst: The Data Analyst agent.
        writer: The Technical Content Writer agent.

    Returns:
        list[Task]: The three tasks in order.
    """

    research_task = Task(
        description=(
            f"Research the topic: '{topic}'.\n\n"
            "Instructions:\n"
            "1. Search the web for the most recent and authoritative information.\n"
            "2. Gather from at least 5-8 credible sources.\n"
            "3. Extract key facts, statistics, dates, and context.\n"
            "4. Note any conflicting viewpoints or controversies.\n"
            "5. Identify current trends and future outlook.\n"
            "6. Organize findings into a structured research brief with source URLs.\n\n"
            "Be thorough — your findings will be used to write the final report."
        ),
        expected_output=(
            "A research brief with 5-8 sourced findings, organized by theme, "
            "with key stats, expert opinions, and source URLs. Minimum 500 words."
        ),
        agent=researcher,
    )

    analysis_task = Task(
        description=(
            f"Analyze the research on '{topic}' and identify the key insights.\n\n"
            "Instructions:\n"
            "1. Review the research brief thoroughly.\n"
            "2. Identify 3-5 major themes or patterns.\n"
            "3. Highlight the most significant statistics and data points.\n"
            "4. Note any gaps or areas needing further investigation.\n"
            "5. Prepare an organized analysis that the writer can use directly.\n\n"
            "Your analysis should make it easy for the writer to create the final report."
        ),
        expected_output=(
            "A structured analysis with 3-5 key themes, supporting data points, "
            "and clear takeaways. Minimum 300 words."
        ),
        agent=analyst,
        context=[research_task],
    )

    writing_task = Task(
        description=(
            f"Write a comprehensive, professional report on '{topic}'.\n\n"
            "The report MUST include these sections in order:\n\n"
            "1. **Title Page** — Topic, date, 'Generated by AI Research Agent'\n"
            "2. **Executive Summary** — 2-3 paragraph overview\n"
            "3. **Introduction** — Context and background\n"
            "4. **Detailed Analysis** — 3-5 subsections with findings\n"
            "5. **Key Insights** — Bullet-pointed takeaways\n"
            "6. **Challenges & Considerations** — Limitations and controversies\n"
            "7. **Future Outlook** — Trends and predictions\n"
            "8. **Sources & References** — Numbered list of all sources\n\n"
            "Format with Markdown (## headings, bullet points, **bold** for emphasis). "
            "Write in a professional, authoritative tone. Target 1500-2000 words."
        ),
        expected_output=(
            "A complete Markdown report with all 8 sections, well-formatted, "
            "factually accurate, and professionally written. Minimum 1500 words."
        ),
        agent=writer,
        context=[research_task, analysis_task],
    )

    return [research_task, analysis_task, writing_task]
