"""Task definitions for the research agent pipeline.

Note: In the new parallel research flow, research is done externally via
research_queue.py. These tasks are only used for the legacy sequential flow
(router.run() -> run()).
"""

import json

from crewai import Task


def make_tasks(topic: str, planner, researcher, analyst, writer):
    """Create the sequential tasks for the research pipeline (legacy).

    For the new parallel flow, use router.run_analysis() instead.

    Args:
        topic: The research topic.
        planner: The Research Planner agent.
        researcher: The Senior Research Analyst agent.
        analyst: The Data Analyst agent.
        writer: The Technical Content Writer agent.

    Returns:
        list[Task]: The four tasks in order.
    """

    planner_task = Task(
        description=(
            f"Create a research plan for the topic: '{topic}'.\n\n"
            "Instructions:\n"
            "1. Decompose the topic into 3-5 focused, actionable sub-questions.\n"
            "2. Each sub-question should target a distinct angle (e.g., market size, key players, "
            "technology, regulation, trends).\n"
            "3. Provide a rationale for why each sub-question matters.\n"
            "4. Suggest an overall research approach.\n\n"
            "Return as valid JSON: {{\"topic\": \"...\", \"sub_questions\": [{{\"question\": \"...\", "
            "\"rationale\": \"...\", \"priority\": 1}}, ...], \"suggested_approach\": \"...\"}}"
        ),
        expected_output=(
            "A JSON research plan with topic, 3-5 sub-questions (each with question, rationale, priority), "
            "and a suggested approach."
        ),
        agent=planner,
    )

    research_task = Task(
        description=(
            f"Research the topic: '{topic}'.\n\n"
            "Instructions:\n"
            "1. Review the research plan and sub-questions provided by the Planner.\n"
            "2. Search the web for the most recent and authoritative information, "
            "focusing on answering each sub-question.\n"
            "3. Gather from at least 5-8 credible sources.\n"
            "4. Extract key facts, statistics, dates, and context.\n"
            "5. Note any conflicting viewpoints or controversies.\n"
            "6. Identify current trends and future outlook.\n"
            "7. Organize findings into a structured research brief with source URLs.\n\n"
            "Be thorough — your findings will be used to write the final report."
        ),
        expected_output=(
            "A research brief with 5-8 sourced findings, organized by theme, "
            "with key stats, expert opinions, and source URLs. Minimum 500 words."
        ),
        agent=researcher,
        context=[planner_task],
    )

    analysis_task = Task(
        description=(
            f"Analyze the research on '{topic}' and identify the key insights.\n\n"
            "Instructions:\n"
            "1. Review the research brief thoroughly.\n"
            "2. Identify 3-5 major themes or patterns.\n"
            "3. Highlight the most significant statistics and data points.\n"
            "4. Note any gaps or areas needing further investigation.\n"
            "5. Prepare an organized analysis that the writer can use directly.\n\n"
            "Your analysis should make it easy for the writer to create the final report."
        ),
        expected_output=(
            "A structured analysis with 3-5 key themes, supporting data points, "
            "and clear takeaways. Minimum 300 words."
        ),
        agent=analyst,
        context=[research_task],
    )

    writing_task = Task(
        description=(
            f"Write a comprehensive, professional report on '{topic}'.\n\n"
            "The report MUST include these sections in order:\n\n"
            "1. **Title Page** — Topic, date, 'Generated by AI Research Agent'\n"
            "2. **Executive Summary** — 2-3 paragraph overview\n"
            "3. **Introduction** — Context and background\n"
            "4. **Detailed Analysis** — 3-5 subsections with findings\n"
            "5. **Key Insights** — Bullet-pointed takeaways\n"
            "6. **Challenges & Considerations** — Limitations and controversies\n"
            "7. **Future Outlook** — Trends and predictions\n"
            "8. **Sources & References** — Numbered list of all sources\n\n"
            "Format with Markdown (## headings, bullet points, **bold** for emphasis). "
            "Write in a professional, authoritative tone. Target 1500-2000 words."
        ),
        expected_output=(
            "A complete Markdown report with all 8 sections, well-formatted, "
            "factually accurate, and professionally written. Minimum 1500 words."
        ),
        agent=writer,
        context=[research_task, analysis_task],
    )

    return [planner_task, research_task, analysis_task, writing_task]
